### ISSUE TITLE
Issues with No Data and multiple stations

### ISSUE THREAD

**Issue by RobertoVillani** [smwesten-usgs/swb2#18]
Hi, I have some issues about No Data, I'm using SWB CODE 1.0:

- In my study area there are No Data pixel, If i put -99999 as No Data in the .asc files (Soil Group, Land Use, Available water capacity, flow direction), the SWB code returns always Error. 

- Same problem if I work with climate at single station. I have not the value of relative humidity, so if i put -99999 in that cells, the SWB code returns an Error. 

- If I work with multiple grid climate stations, how should i write this parameter in the SWB code?

- I'm working with mm and °C data. So, how can i convert these in inch and F directly writing it in the code?

The image is an example of the -99999 error with the .asc files.
![Immagine](https://user-images.githubusercontent.com/63255922/78588730-6c17e700-783f-11ea-9235-39b8c9f6deb2.png)

Thank you.

**Comment by smwesten-usgs** [comment]
Hi Roberto, 

I am closing this issue as your problem pertains to an earlier version of the code (smwesten-usgs/swb).

If possible, please email me a copy of the logfile (named something like SWB_LOGFILE_xxx.txt). I think we can get you pointed in the right direction!

 - Steve

smwesten@usgs.gov

**Comment by RobertoVillani** [comment]
Roberto Villani <villaniroberto95@gmail.com>
[image: Allegati]13:06 (24 minuti fa)
a *smwesten-usgs/swb2*
Logfile_000 is an example of No Data problem (We try to put 0 as No Data
and it doesn't work, same with -99999).

Logfile_Skip is an example of the Code that doesn't read the -99999
Humidity values in the climate .txt files.


Thank You

Il giorno lun 6 apr 2020 alle ore 21:20 Steve Westenbroek <
notifications@github.com> ha scritto:
