### ISSUE TITLE
SWB CODE

### ISSUE THREAD

**Issue by amrdeeb** [smwesten-usgs/swb2#22]
How do I solve this problem?
Is there an example with full data for multiple stations?

** FATAL ERROR - HALTING SWB **

Cannot read integer data value for ending year of simulation

**Comment by smwesten-usgs** [comment]
Greetings,

It is difficult to know what is going on given the error message alone. I suspect that you are using SWB version 1.x; this repository contains codes and issues pertaining to the SWB 2.x version. 

The SWB 1.x code accepts tabular data for a single location only. If you have precipitation and temperature data for more than one site, the data must be supplied to SWB in gridded form, one grid per day. The SWB 2.x code does not currently have a reliable way to accept tabular precipitation and temperature data.

If you like, send me a copy of your control file, log file (i.e. SWB_LOGFILE*) and precipitation file (if you have one) and I would be happy to offer suggestions. EMail is smwesten@usgs.gov

 - Steve

**Comment by amrdeeb** [comment]
Thanks Mr Westenbroek, i solved the issue.

Best Regards.


Eng.Amr Deeb
Civil Engineer
+972567860499
+972598860499

________________________________
